Add files via upload
KristinaKuslina/home_task1 pull request #12
Opened 2019-11-11 17:09 UTC by KristinaKuslina

my fifth homework

2019-11-17 09:59 UTC, illarionovEA requested changes
с моделированием случайного блуждания что-то не то. Длина пути должна быть ровно 100. Начало и конец в 0.

2019-11-17 14:35 UTC, KristinaKuslina commented
Но ведь задание формулируется так, что нужно найти блуждание именно на решетке длины n, т.е. за границы 100 на 100 выходить нельзя, а не за n шагов, или я что-то не так понимаю тут ... 
"Напишите функцию, которая моделирует случайное симметричное блуждание на двумерной решетке длины n c началом и концом в точке (0, 0). Приведите графики выборочных траекторий для n=100."

2019-11-17 15:59 UTC, illarionovEA commented
слово длина относится к траектории блуждания

2019-11-19 15:03 UTC, KristinaKuslina commented
Я переделала задачу со случайным блужданием.

2019-11-22 16:07 UTC, illarionovEA approved these changes

2019-11-29 16:49 UTC, KristinaKuslina commented
my 5th home work

2019-11-29 16:49 UTC, merged